[features]
seeds = false
skip-lint = false

[programs.localnet]
cloak_gatekeeper = "AgFx8yS8bQnXSCSGfN3f8oz3HJGeF5rwLoWtfHTEEaAq"
cloak_squads_test_harness = "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf"

[programs.devnet]
cloak_gatekeeper = "AgFx8yS8bQnXSCSGfN3f8oz3HJGeF5rwLoWtfHTEEaAq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/cloak-devnet.json"

[scripts]
test = "pnpm test:int"
