[features]
seeds = false
skip-lint = false

[programs.localnet]
cloak_mock = "9oNHUEqLVcUBygReEgy26yxDSAPFUi48bb2MJ4UsqQJr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test:int"
